---
title: "Lec 27: Interactive Maps"
subtitle: "SDS 192: Introduction to Data Science"
author: |
  Shiya Cao<br/>
  <span style = 'font-size: 70%;'>
  [Statistical & Data Sciences](http://www.smith.edu/sds), Smith College<br/>
  </span>
date: |
  Fall 2022<br/>
  `r sds::img_logo(width = 64)`
output:
  sds::moon_reader:
    lib_dir: libs
    css: xaringan-custom.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false    
      navigation:
        scroll: false
---


# Today's Learning Goals

* Create interactive maps in `leaflet`.

---

# `leaflet` for R
  
* Start by calling `leaflet()` function, setting the original view, and adding basemap tiles.


```r
library(leaflet)

leaflet() |>
  addTiles() |> 
  addMarkers(
    lng=-72.638139,
    lat=42.318119,
    popup="Smith College"
      )
```

---

# `leaflet` Supports `sf`
      
```r
library(sf)
nc &lt;- system.file("shape/nc.shp", package = "sf") |>
  st_read()
```
      
```
## Reading layer `nc' from data source `/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/sf/shape/nc.shp' using driver `ESRI Shapefile'
## Simple feature collection with 100 features and 14 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
## Geodetic CRS:  NAD27
```
     
```r
class(nc)
```

```
## [1] "sf"         "data.frame"
```

---

# Plotting `sf` objects in `leaflet`
      
```r
leaflet() |>
  addTiles()|>
  addPolygons(data=st_transform(nc,4326))
```

---
      
# Projections Checklist
      
* Are you using `leaflet`?
      * Project everything in EPSG 4326.
* Are you using `ggplot2`?
      * Choose a projection scheme that is appropriate for your data.
      * Project everything in that scheme.

---
      
# `macleish` Package

* Weather data
      * Temperature, wind speed, humidity, pressure, rainfall, etc.
* Spatial data
      * Buildings, streams, forests, slopes, etc.

      
```r
install.packages("macleish")
```

---
      
# Checking Projections
      
```r
macleish_layers |>
  pluck("buildings") |>
  st_crs()
```      
     
```
Coordinate Reference System:
  User input: EPSG:4326 
  wkt:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Horizontal component of 3D system."],
        AREA["World."],
        BBOX[-90,-180,90,180]],
    ID["EPSG",4326]]
```
      
---
      
# Projecting Geospatial Data
      
```r
buildings_3857 <- macleish_layers |>
  pluck("buildings") |>
  st_transform(3857)

buildings_3857 |>
  st_crs()
```      
     
```
Coordinate Reference System:
  User input: EPSG:3857 
  wkt:
PROJCRS["WGS 84 / Pseudo-Mercator",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["Popular Visualisation Pseudo-Mercator",
        METHOD["Popular Visualisation Pseudo Mercator",
            ID["EPSG",1024]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Web mapping and visualisation."],
        AREA["World between 85.06°S and 85.06°N."],
        BBOX[-85.06,-180,85.06,180]],
    ID["EPSG",3857]]
```      

---
      
# Colors in `leaflet`
      
```r
library(macleish)
      
leaflet() |>
  addTiles()|>
  addPolygons(data = pluck(macleish_layers, "wetlands"), 
              color = ~SHAPE_AREA, popup = ~IT_VALDESC)
```

---
      
# `leaflet` Uses Color Palette Functions
      
* For numerical variables:
      * `colorNumeric()`: Maps numbers to colors in a specified palette.
      * `colorBin()`: Maps numbers into a specified intervals (e.g. 0-10, &gt;10-20, etc.).
      * `colorQuantile()`: Maps numbers into a specified number of buckets (intervals calculated automatically).
* For categorical variables:
      * `colorFactor()`: Maps categories into a specified number of buckets.
* All take two arguments:
      * `palette` (can be `RColorBrewer` or `viridis`).
      * `domain` (can be `NULL`).

---

# Step 1: Define the Color Palette

.pull-left[
      
```r
wetland_pal <- colorNumeric(
  palette = "viridis", 
  domain = macleish_layers |>
    pluck("wetlands") |>
    pull(SHAPE_AREA)
)
```

* This is now a function that
      * takes an **area**
      * returns an HTML **color**
]
      
.pull-right[

```r
wetland_pal(2000)
```

```
[1] "#471164"
``` 

```r
wetland_pal(5000)
```

```
[1] "#3D4D8A"
```

---

# Step 2: Use the Palette to Map to Color
      
```r
leaflet() |>
  addTiles() |>
  addPolygons(data = pluck(macleish_layers, "wetlands"), 
              color = ~wetland_pal(SHAPE_AREA), 
              fillOpacity = 0.8, weight = 0.1, 
              popup = ~IT_VALDESC)
```
