---
title: "Syllabus"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: no
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, message=FALSE, warning = FALSE, eval = TRUE, 
  fig.width = 16/2, fig.height = 9/2
)

# Set seed value of random number generator to get "replicable" random numbers.
# Why 76? Because of https://www.youtube.com/watch?v=xjJ7FheCkCU
set.seed(76)
```

<!--
{target="_blank"}
-->

<style>
h1{font-weight: 400;}
</style>


# Basic Information {#basicinfo}

* **Course title**: SDS 192 Introduction to Data Science
* **Instructor**: Shiya Cao - Assistant Professor of Statistical & Data Sciences
* **Office location**: 
* **~~Email:~~ Slack team**: Click hashtag icon in navbar for the browser interface or use the [desktop/mobile app](https://slack.com/downloads/){target="_blank"}.
* **Meeting locations/times**: MWF 10:50 AM - 12:05 PM / Sabin-Reed 220
* **Getting help**:
    + For non personal/sensitive questions, ask on the `#sds-192-questions` channel on Slack. For personal/sensitive matters, Slack DM me.
    + Spinelli Center [SDS drop-in tutoring hours](https://www.smith.edu/qlc/tutoring.html?colStats=open#PanelStats.){target="_blank"}. In Sabin-Reed 301
        + Sunday through Thursday 7-9pm
    + **Office hours**:
        + Before coming to office hours, please have your question ready on your computer. 
        + During in-person office hours, you can work in the nearby SDS student lounge in McConnell 209. During virtual office hours, you can stay with your screen off and work or listen to other student's questions. 
        + If the regularly scheduled times do not work for you, please Slack DM me.
    + [Data Research and Statistics Counselor](https://www.smith.edu/qlc/tutoring.html?colDataCnslr=open#PanelDataCnslr){target="_blank"} Osman Keshawarz



## Instructor work-life balance {#work-life-balance}

* I will respond to Slack messages sent during the week within 24h. I will respond to Slack messages sent during the weekend at my own discretion. It is important that you plan when you start your assignments accordingly.
* If possible, please only Slack me with briefer and administrative questions; I prefer having more substantive conversations in person as it takes me less energy to understand where you are at.
* I will do my best to return all grading as promptly as possible.



***



# How Can I Succeed in This Class?

Ask yourself:

* **When I have questions or don't understand something:**
    + *"Am I asking questions in class?"*
    + *"Am I asking questions on Slack in the `#sds-192-questions` channel?"* Even better: *"Am I answering my peers' questions on Slack?"*
    + *"Having I been going to the Spinelli tutoring center for help on R and the tidyverse?"*
    + *"Have I been coming to office hours?"*
* **Lectures and readings:**
    + *"Am I staying on top Slack notifications sent between lectures?"* If you need help developing a notification strategy that best suits your lifestyle, please speak to me. 
    + *"Am I attending lectures consistently?"*
    + *"During in-class exercises, am I actually running code line-by-line and studying the outputs? Am I taking full advantage that I'm in the same place at the same time with the instructor, the lab assistants, and most importantly your peers, or am I browsing the web/texting the whole time?"*
    + *"Have I been doing the associated readings for each lecture?"*



***



# Course Description & Objectives

From [Smith College Course Search](https://www.smith.edu/academics/academic-program/curriculum/course-search?term=Fall+2019&dept=&instr=Albert+Y.+Kim&credits=&course_numb=192&course_keywd=&op=Submit&form_build_id=form-V3WH-ixzbA-eyjFrRcImqp_C6DNgVUwcb_Pg8XhbUS8&form_id=campus_course_search_basic_search_form){target="_blank"}: *An introduction to data science using Python, R and SQL. Students learn how to scrape, process and clean data from the web; manipulate data in a variety of formats; contextualize variation in data; construct point and interval estimates using resampling techniques; visualize multidimensional data; design accurate, clear and appropriate data graphics; create data maps and perform basic spatial analysis; and query large relational databases. No prerequisites, but a willingness to write code is necessary.*

On top of the goals of the above description, this semester you will:

1. Equip yourselves with the data science tools necessarily to perform effective *exploratory data analysis*.
1. Learn about project workflows such as
    + Getting a ["minimally viable product"](https://www.interaction-design.org/literature/article/minimum-viable-product-mvp-and-design-balancing-risk-to-gain-reward){target="_blank"} done *quickly*.
    + Not ["letting the perfect be the enemy of the good"](https://www.entrepreneur.com/article/249676){target="_blank"}.
1. Understand common issues related to data ethics throughout the course.



***



# Lecture Schedule {#topicschedule}

The lecture schedule and associated readings can be found on the [main page](index.html){target="_blank"} of this course webpage. The ModernDive textbook is accessible on the navigational bar of this webpage. 

## Class norms {#policies}

* Bring your laptop, a set of headphones, colored pens/pencils with paper notebook (or tablet with stylus) to every lecture.
* You are expected to stay until the end of lecture. If you need to leave early, please confirm with me at the beginning of lecture and sit somewhere where your departure will be minimally disruptive. 
* Attendance will not be explicitly taken and occasional absences are excused. However, extended absences should be mentioned to me.
* However, you are responsible for asking your peers for what you missed. For example, makeup lectures will not be held during office hours.
* Lecture will be held as usual on Monday 11/21 (before Thanksgiving).



***



# Evaluation

All due dates can be found on the [main page](index.html){target="_blank"} of this course webpage.

## Midterms 35%

There will be two midterms during the semester. The higher score of the two midterm scores will be weighted 20% and the lower will be weighted 15%. More details to follow.

<!--
You'll take these midterms in Seelye Self-Scheduled Exam center between Friday at 5pm and Sunday at 11:55pm. Instructions on taking exams for [Smithies](https://sophia.smith.edu/edtech/documentation/print-an-exam-from-the-direct-to-queue-application/){target="_blank"} and [Five College Students](https://sophia.smith.edu/edtech/documentation/special-instructions-for-five-college-and-high-school-students-using-direct-to-queue-exam-printing/){target="_blank"}.

* Midterm I: Data visualization
* Midterm II: Data wrangling
-->




## Three mini-projects 30%

There will be three mini-projects with particular themes. You'll do these mini-projects in groups of 2 assigned by me. 

* Mini-project 1 5%: Data visualization
* Mini-project 2 10%: Data wrangling
* Mini-project 3 15%: Mapping

**Late assignments**: I understand that you will sometimes need to prioritize other things over meeting assignment deadlines (e.g., your health, wellness, families, communities, jobs, and other coursework). My late policy attempts to balance flexibility with accountability. There is a 24-hour grace period on all mini-project assignments. There will be no penalties for submitting the mini-project within this 24-hour period, and you do not need to inform me that you intend to take the extra time. You can also request up to a 72-hour extension on any mini-project assignment, as long as you make that request at least 48 hours before the original assignment due date. Please note that because the mini-project assignments are collaborative, communicate in your group about the intended late submission first.


## Final project 20%

There will be a final project due the last day of exams. You'll do this final project in groups of 2-3 where you can choose your groupmates. 

As for whether you should be on Smith campus during exam week, this is for you and your groupmates to decide. You do not need to consult the instructor. 


## Problem sets 10%

There will be 7 problem sets, with only the top 5 scores going towards your grade. Since the lowest two grades will be dropped, no extensions to problem sets will be given.


## Engagement 5% {#engagement}

It is difficult to explicit codify what constitutes "an engaged student," so
instead I present the following rough principle I will follow: *you'll only get
out of this class as much as you put in*. That being said, here are multiple
pathways for you to stay engaged in this class:

* In particular: Peer evaluations for all projects.
* Asking and answering questions in class.
* Coming to office hours.
* Posting questions on Slack.
* Even better: Responding to questions on Slack.





## Policies

1. **Collaboration**: While I encourage you to work with your peers for problem
sets, you must submit your own answers and not simple rewordings of
another's work. Furthermore, all collaborations must be explicitly acknowledged
in your submissions.
1. **Honor Code**: All your work must follow the [Smith College Academic Honor
Code Statement](https://www.smith.edu/about-smith/offices/student-affairs/student-handbook/academic-honor-code-0#:~:text=Honor%20Code%20Statement&text=Smith%20College%20expects%20all%20students,of%20course%20work%20and%20examinations.){target="_blank"};
in particular all external sources must be cited in your submissions.
<!--
1. **Problem sets**:
    + No extensions on problem sets. However, only top 5 out of 7 scores count for your grade.
1. **Mini-projects**:
    + Extensions only with a dean's note.
1. **Midterms**:
    + No make-up midterms will be allowed without a dean's note. 
    + Timestamps for all midterms will be strictly enforced.
-->
1. **Grading**: I reserve the right to not discuss any grading issues in class and instead direct you to office hours. 




***



# Accommodations {#accommodations}
 
It is my goal for everyone to succeed in this course. If you have personal circumstances that may impact your experience of our classroom, I encourage you to contact <a href="https://www.smith.edu/about-smith/disability-services" target="_blank">Office of Disability Services</a> in College Hall 104 or at 413-585-2071 or at <a href="mailto:ods@smith.edu">ods@smith.edu</a>. The Office will generate a letter that indicates to me what kind of support you need and how I can make your classroom experience more accommodating. Once you have this letter, you are welcome to visit my office hours or email me to discuss ideas about how we can tailor the course accordingly. While you can request accommodations at any time, the sooner we start this conversation, the better. If you have concerns about the course that are not addressed through ODS, please contact me. At no point will I ask you to divulge details about your personal circumstances to me.




***



# Student Well-being {#studentwellbeing}
 
College life is stressful, and life outside of college can be overwhelming. It is my position that attending to your physical and mental health and well-being should be a top priority. I will remind you of this often throughout the quarter. I encourage you to schedule a time to talk with me if you are struggling with this course. If you, or anyone you know, is experiencing distress, there are numerous campus resources that can provide support via the Schacht Center (https://www.smith.edu/student-life/health-wellness). I can point you to these resources at any time throughout the quarter.

Getting help is a smart and courageous thing to do -- for yourself and for those who care about you.



***



# Group Dynamics {#groupdynamics}
Working in a group can be challenging at times. I hope that we can foster a collaborative and caring environment in this classroom.

## Care for each other

* If your groupmate (and any other classmate) helps you out on an assignment, says something brilliant that solidifies the material for you, or just listens when you&#39;ve had a bad day, give them a shout-out on our <code>#sds-192-appreciation</code> Slack channel. 
* Check-in with colleagues before starting collaborative work. &ldquo;What three words describe how you&#39;re feeling?&rdquo; &ldquo;Name one challenge and one success from this week.&rdquo; &ldquo;What are you doing for self-care right now?&rdquo; Thank each other for sharing where they&#39;re at.
* Cheer on colleagues as they give presentations or try something out for the first time.</li>
* Ask questions often in our <code>#sds-192-questions</code> channel. Help each other out by answering questions when you can. 

I also suggest that your group defines roles in the group. Your group will function better when everyone has a clear understanding of their roles and responsibilities.

## Define roles

* No one should have a role that doesn’t involve writing R (or SQL) code. Learning how to write code is an essential part of this course, so if you aren’t doing that, you won’t be able to achieve the learning goals of the course.
* Groups should be non-hierarchical. Leaders may emerge naturally and that is great, but no one in the group is the boss. Decisions should be made as a group.
* Leaving someone out—regardless of the reasons—exemplifies poor leadership. If a group member is struggling to keep up, help them. If a group member is not carrying their weight, talk to them. Ignoring interpersonal conflicts will not make them go away. The goal of working in groups in this class is to equip you with skills to collaborate effectively and equitably in groups throughout your careers.

# Code of Conduct {#codeofconduct}

As the instructor and assistants for this course, we are committed to making
participation in this course a harassment-free experience for everyone,
regardless of level of experience, gender, gender identity and expression,
sexual orientation, disability, personal appearance, body size, race, ethnicity,
age, or religion. Examples of unacceptable behavior by participants in this
course include the use of sexual language or imagery, derogatory comments or
personal attacks, trolling, public or private harassment, insults, or other
unprofessional conduct.

As the instructor and assistants we have the right and responsibility to point
out and stop behavior that is not aligned to this Code of Conduct. Participants
who do not follow the Code of Conduct may be reprimanded for such behavior.
Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the instructor.

**All students, the instructor, the lab instructor, and all data assistants are
expected to adhere to this Code of Conduct in all settings for this course:
lectures, office hours, tutoring hours, and over Slack.**

This Code of Conduct is adapted from the [Contributor
Covenant](http://contributor-covenant.org){target="_blank"}, version 1.0.0,
available [here](http://contributor-covenant.org/version/1/0/0/){target="_blank"}.



